version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fitness
      POSTGRES_USER: fitness
      POSTGRES_PASSWORD: fitness
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "63790:6379"
  backend:
    build: ../backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ../backend/.env.example
    volumes:
      - ../backend:/code
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
      - redis
  frontend:
    build: ../frontend
    command: npm run start -- --hostname 0.0.0.0 --port 3000
    volumes:
      - ../frontend:/app
    ports:
      - "127.0.0.1:3001:3000"
    depends_on:
      - backend
volumes:
  pgdata:
